config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "texts#index"
  resources :users
    resources :texts do
    collection do
      get 'search' #=> 'texts#search'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tag.rb
class Tag < ApplicationRecord
 

  has_many :text_tag_relations, dependent: :destroy
  has_many :texts, through: :text_tag_relations

  validates :tag_name, presence: true, uniqueness: true
  def self.search(search)
    if search != '#'
      Tag.where('sentence LIKE(?)', "%#{search}%")
      
    else
      Text.all
    end
  end

end

app/models/text.rb
class Text < ApplicationRecord
  
  extend ActiveHash::Associations::ActiveRecordExtensions
  has_many :text_tag_relations, dependent: :destroy
  has_many :tags, through: :text_tag_relations
  belongs_to :type
  belongs_to :user
  belongs_to_active_hash :type


  with_options presence: true do
  validates :sentence
  validates :translate
  validates :type_id
  end
  
 
  def self.search(search)
    if search != ""
      Text.where(['sentence LIKE (?) OR translate LIKE(?)', "%#{search}%", "%#{search}%"])
    else
      Text.all
    end
  end
 
  
end

app/models/text_tag_relation.rb
class TextTagRelation < ApplicationRecord
  belongs_to :text
  belongs_to :tag
end

app/models/type.rb
class Type < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: 'カジュアル' },
    { id: 3, name: 'フォーマル' },
  ]

  include ActiveHash::Associations
  has_many :texts

  end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
        
         has_many :texts

         validates :password, format: { with: /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]+\z/i, message: '. Include both letters and numbers' }
         validates :nickname, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!
 
  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end
 
end

app/controllers/texts_controller.rb
class TextsController < ApplicationController
  before_action :set_text, only: [:show, :edit, :update, :destroy]

  def index
    
    @texts = params[:tag_id].present? ? Tag.find(params[:tag_id]).texts : Text.all
    
  end

  def new
    @text = Text.new
  end

  def create
    @text = Text.new(text_params)
    if @text.valid?
      @text.save
      redirect_to root_path
    else
      render :new
    end
  end

  def destroy
    @text.destroy
    redirect_to root_path
  end

  def edit
    #text_attributes = @text.attributes
    #@text_form = TextForm.new(text_attributes)
    #@text_form.tag_name = @text.tags&.first&.tag_name
    redirect_to root_path unless current_user.id == @text.user_id
  end

  def update
    #@text = Text.new(text_params)
    if @text.valid?
      @text.update(text_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  def show
   
  end

  def search
    @texts = Text.search(params[:keyword])
  end


  private
  def text_params
    params.require(:text).permit(:sentence, :translate, :remarks, :type_id, tag_ids: []).merge(user_id: current_user.id)
  end

  def set_text
    @text = Text.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @nickname = current_user.nickname
    @texts = current_user.texts
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/texts_helper.rb
module TextsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sentence</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" type="text/css" href="http://yui.yahooapis.com/3.18.1/build/cssreset/cssreset-min.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  
    <%= yield %>
  </body>
</html>

app/views/texts/_main_page.html.erb
<div class="main-header">
  <div class="form-input">
  
    <%= form_with(url: search_texts_path, local: true, method: :get, class: "search-form") do |form| %>
    <%= form.text_field :keyword, placeholder: "英文・英単語で検索", class: "form-search" %>
    <%#= form.submit "検索", class: "search-btn" %>
    <% end %>
  </div>
  <%= form_tag texts_path, method: :get, class: 'boards__searchForm' do %>
      <%= select_tag :tag_id,
                     options_from_collection_for_select(Tag.all, :id, :tag_name, params[:tag_id]),
                     {
                       prompt: 'タグで絞り込み検索',
                       onchange: 'submit(this.form);'
                     }
      %>
    <% end %>
</div>

<div class="main-form">
    <div class="sentence">
      <% @texts.each do |text| %>
        <div class="english">
          <div class="english-text">
      <%= link_to text.sentence, text_path(text.id)%>
          </div>
        </div>
     <div class="japanese">
        <div class="japanese-text">
        <%= text.translate %>
       
        </div>
      </div>
      <% end %>

    </div>
</div>


  



<div class="footer">
</div>

app/views/texts/_side_bar.html.erb
<div class="side-header">
  <div class="header-name">
    <%= current_user.nickname %>
  </div>
   <div class="delete-button">
    <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'btn'%>
  </div>
</div>

<div class="side-form">
  <div class="side-menu">
    <ul class="menu-bar">
    <li><%= link_to 'ホーム', root_path, method: :GET %></li>
      <li><%= link_to '文章を登録', new_text_path, method: :GET %></li>
      <li><%# @tag_lists.each do |list|%></li>
        
        <%#= link_to "", list.tag_name, texts_path(tag_id: list.id), class: 'tag_list' %>
      
    </ul>
  </div>
</div>

app/views/texts/edit.html.erb
<div class="new-wrapper">
    <div class="main-title">
   <h1>文章の編集</h1>
  </div>
  <div class='text-registration'>
    <%=form_with model: @text, url: text_path(@text.id), method: :patch, local: true do |f|%>
      <div class='text-registration__field'>
        <div class='text-registration__field--left'>
          <%= f.label :英文, class: 'text-registration__label'%>
        </div>
        <div class='text-registration__field--right'>
          <%= f.text_field :sentence, class: 'text-registration text-registration__input', placeholder: '英文を入力してください'%>
        </div>
      </div>
      <div class='text-registration__field'>
        <div class='text-registration__field--left'>
          <%= f.label :和訳, class: 'text-registration__label'%>
        </div>
        <div class='text-registration__field--right'>
          <%= f.text_field :translate, class: 'text-registration text-registration__input', placeholder: '和訳を入力してください'%>
        </div>
      </div>

  <div class='text-registration__field'>
        <div class='text-registration__field--left'>
          <%= f.label :備考, class: 'text-registration__label'%>
        </div>
        <div class='text-registration__field--right'>
          <%= f.text_field :remarks, class: 'text-registration text-registration__input', placeholder: '備考を入力してください(任意)'%>
        </div>
      </div>

    <div class='text-registration__field'>
        <div class='text-registration__field--left'>
          <%= f.label :タグ, class: 'text-registration__label'%>
        </div>
         <div class='text-registration__field--right'>
          <div class="check_box">
          <span>タグ</span>
            <%= f.collection_check_boxes(:tag_ids, Tag.all, :id, :tag_name) do |tag| %>
            <div>
              <%= tag.label do %>
                <%= tag.check_box %>
                <%= tag.text %>
              <% end %>
            </div>
          <% end %>
          </div>
       
        </div>
        </div>

   <div class='text-registration__field'>
        <div class='text-registration__field--left'>
          <%= f.label :文章タイプ, class: 'text-registration__label'%>
        </div>
        <div class='text-registration__field--right'>
          <%= f.collection_select(:type_id, Type.all, :id, :name, {}, {class:"type-select"}) %>
        </div>
      </div>



      <div class='text-registration__field'>
      </div>
      
      <div class='text-btn__field'>
        <div class='text-registration__field--left'></div>
        <div class='btn-field'>
        <div class='submit-btn'>
          <%= f.submit "更新", class: 'text-registration__action-btn'%>
        </div>
        <div class='root-btn'>
          <%= link_to "戻る", text_path, class: 'text-registration__action-btn'%>
        </div>
        </div>
      </div>
    </div>
    <% end %>
</div>

app/views/texts/index.html.erb
<div class="wrapper">
  <div class="side">
  <%= render "side_bar" %>
  </div>
  <div class="main">
  <%= render "main_page" %>
  </div>
</div>

app/views/texts/new.html.erb
<div class="new-wrapper">
<div class="main-title">
   <h1>文章の登録</h1>
  </div>
    
  <div class='text-registration'>
    <%=form_with model: @text, url: texts_path, method: :post, id: 'new_post',local: true do |f|%>
      <div class='text-registration__field'>
        <div class='text-registration__field--left'>
          <%= f.label :英文, class: 'text-registration__label'%>
        </div>
        <div class='text-registration__field--right'>
          <%= f.text_field :sentence, class: 'text-registration text-registration__input', placeholder: '英文を入力してください'%>
        </div>
      </div>
      <div class='text-registration__field'>
        <div class='text-registration__field--left'>
          <%= f.label :和訳, class: 'text-registration__label'%>
        </div>
        <div class='text-registration__field--right'>
          <%= f.text_field :translate, class: 'text-registration text-registration__input', placeholder: '和訳を入力してください'%>
        </div>
      </div>

    <div class='text-registration__field'>
          <div class='text-registration__field--left'>
            <%= f.label :備考, class: 'text-registration__label'%>
          </div>
          <div class='text-registration__field--right'>
            <%= f.text_field :remarks, class: 'text-registration text-registration__input', placeholder: '備考を入力してください(任意)'%>
          </div>
    </div>

     <div class='text-registration__field'>
        <div class='text-registration__field--left'>
          <%= f.label :タグ, class: 'text-registration__label'%>
        </div>
         <div class='text-registration__field--right'>
          <div class="check_box">
          <span>タグ</span>
            <%= f.collection_check_boxes(:tag_ids, Tag.all, :id, :tag_name) do |tag| %>
            <div>
              <%= tag.label do %>
                <%= tag.check_box %>
                <%= tag.text %>
              <% end %>
            </div>
          <% end %>
          </div>
       
        </div>
        </div>


   <div class='text-registration__field'>
        <div class='text-registration__field--left'>
          <%= f.label :文章タイプ, class: 'text-registration__label'%>
        </div>
        <div class='text-registration__field--right'>
          <%= f.collection_select(:type_id, Type.all, :id, :name, {}, {class:"type-select"}) %>
        </div>
      </div>



       
      
      <div class='text-btn__field'>
        <div class='text-registration__field--left'></div>
        <div class='btn-field'>
        <div class="submit-btn">
          <%= f.submit "保存", class: 'text-registration__action-btn'%>
        </div>
        <div class="root-btn">
          <%= link_to "戻る", root_path, class: 'text-registration__action-btn'%>
        </div>
        </div>
      </div>


    </div>
    <% end %>
</div>

app/views/texts/search.html.erb
<div class="wrapper">
  <div class="side">
    <%= render "side_bar" %>
  </div>
  <div class="main">
 <div class="main-header">
  <div class="form-input">
 
   <%= form_with(url: search_texts_path, local: true, method: :get, class: "search-form") do |form| %>
    <%= form.text_field :keyword, placeholder: "英文・英単語で検索", class: "form-search" %>
    <div id="search-result"></div>
    <% end %>
  </div>
  <%= form_tag texts_path, method: :get, class: 'boards__searchForm' do %>
      <%= select_tag :tag_id,
                     options_from_collection_for_select(Tag.all, :id, :tag_name, params[:tag_id]),
                     {
                       prompt: 'タグで絞り込み検索',
                       onchange: 'submit(this.form);'
                     }
      %>
    <% end %>
</div>

<div class="main-form">
    <div class="sentence">
      <% @texts.each do |text| %>
        <div class="english">
          <div class="english-text">
          <%= link_to text.sentence, text_path(text.id) %>
          </div>
        </div>
     <div class="japanese">
        <div class="japanese-text">
        <%= text.translate %>
      
        </div>
      </div>
      <% end %>
    </div>
</div>

<div class="footer">
</div>
</div>
</div>

app/views/texts/show.html.erb
<div class="new-wrapper">
  <div class="main-title">
    <h1 id="js-copytext"><%= @text.sentence %></h1>
  <button type="button" id="js-copybtn">Copy</button>
  </div>
  <div class='text-registration'>
    <%=form_with model: @text, local: true do |f|%>
     
      <div class='text-registration__field'>
        <div class='text-registration__field--left'>
          <%= f.label :和訳, class: 'text-registration__label'%>
        </div>
        <div class='text-registration__field--right'>
        
          <%= @text.translate %>
        </div>
      </div>

  <div class='text-registration__field'>
        <div class='text-registration__field--left'>
          <%= f.label :補足, class: 'text-registration__label'%>
        </div>
        <div class='text-registration__field--right'>
          <%= @text.remarks %>
        </div>
      </div>

  <div class='text-registration__field'>
        <div class='text-registration__field--left'>
          <%= f.label :タグ, class: 'text-registration__label'%>
        </div>
        <div class='tag-list'>
          <% @text.tags.each do |tag| %>
          <%= tag.tag_name %>
          <% end %>

        </div>
      </div>

   <div class='text-registration__field'>
        <div class='text-registration__field--left'>
          <%= f.label :文章タイプ, class: 'text-registration__label'%>
        </div>
        <div class='text-registration__field--right'>
          <%= @text.type.name %>
        </div>
      </div>

      <div class='text-registration__field'>
        <div class='text-registration__field--left'>
          <%= f.label :投稿者, class: 'text-registration__label'%>
        </div>
        <div class='text-registration__field--right'>
          <%= @text.user.nickname %>
        </div>
      </div>



      <div class='text-registration__field'>
        <div class='text-registration__field--left'>
      
      
      <div class="btn-field">
        <div class='text-registration__field--right'>
        <% if user_signed_in? && current_user.id == @text.user_id %>
          <%= link_to "編集",  edit_text_path(@text.id), method: :get, class: 'text-registration__action-btn' %>
        <% end %>
        </div>
        <div class='text-registration__field--right'>
        <% if user_signed_in? && current_user.id == @text.user_id %>
          <%= link_to "削除", text_path(@text.id), method: :delete, class: 'text-registration__action-btn'%>
          <% end %>
        </div>
        
         <div class='text-registration__field--right'>
          <%= link_to "戻る", root_path, class: 'text-registration__action-btn'%>
        </div>
      </div>
    </div>
    </div>
    <% end %>
</div>

app/views/users/_side_user.html.erb
<div class="side-header">
  <div class="header-name">
    <%= link_to current_user.nickname, "/users/#{current_user.id}" %>
  </div>
   <div class="delete-button">
    <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'btn'%>
  </div>
</div>

<div class="side-form">
  <div class="side-menu">
    <ul class="menu-bar">
    <li><%= link_to 'ホーム', root_path, method: :GET %></li>
      <li><%= link_to '文章を登録', new_text_path, method: :GET %></li>
      <li><%# @tag_lists.each do |list|%></li>
        
        <%#= link_to "", list.tag_name, texts_path(tag_id: list.id), class: 'tag_list' %>
      
    </ul>
  </div>
</div>

app/views/users/show.html.erb
<div class="wrapper">
  <div class="side">
    <%= render "side_user" %>
  </div>
  <div class="main">
 <div class="main-header">
  <div class="mypage-title">
  <%= @nickname %>さんの投稿一覧
  </div>
  
</div>


<div class="main-form">
    <div class="sentence">
      <% @texts.each do |text| %>
        <div class="english">
          <div class="english-text">
          <%= link_to text.sentence, text_path(text.id) %>
          </div>
        </div>
     <div class="japanese">
        <div class="japanese-text">
        <%= text.translate %>
        <div class="text-type">
        ＜<%= text.type.name%>＞
        </div>
        </div>
      </div>
      <% end %>
    </div>
</div>

<div class="footer">
</div>
</div>
</div>